[package]
name = "start-cli"
version = "0.1.0"
edition = "2021"
description = "Starter Cli"
repository = "https://github.com/hurtadosanti/start-cli"
[dependencies]
dialoguer = "0.11.0"
console = "0.15.8"